### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by vv12131415** [spatie/checklist-going-live#5]
Thank's for the checklist - I have an idea to translate it to Russian, can I?
I might need some proofreading for it so it will be translated right way.

**Comment by sebastiandedeyne** [comment]
Not sure if it's a good idea to keep it in this repository, since we'd have to maintain something we don't understand.

How about you fork this / create your own repository and we add a link to it?

Anyway, let's see what @freekmurze thinks first :)

**Comment by freekmurze** [comment]
Thanks for your proposal, but like @sebastiandedeyne said, we can't maintain stuff in Russian, so we're going to pass on this.

Feel free to create your own fork where you add and maintain the Russian translation.
